package xyz.mlserver.mod.mlservermodchecker;

import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;
import org.apache.logging.log4j.Logger;
import xyz.mlserver.mod.mlservermodchecker.commands.ModCheckCmd;
import xyz.mlserver.mod.mlservermodchecker.listeners.ForgeConfigChangeListener;
import xyz.mlserver.mod.mlservermodchecker.listeners.ForgeServerLoginListener;

@Mod(modid = MLServerModChecker.MODID, name = MLServerModChecker.NAME, version = MLServerModChecker.VERSION)
public class MLServerModChecker
{
    public static final String MODID = "mlservermodchecker";
    public static final String NAME = "MLServer Mod Checker";
    public static final String VERSION = "1.0.0";

    private static Logger logger;

    public static Loader loader;

    @EventHandler
    public void preInit(FMLPreInitializationEvent event) {
        logger = event.getModLog();
        loadInfo(event.getModMetadata());
        // MLServerModCheckerConfigCore.loadConfig(event);
    }

    @EventHandler
    public void init(FMLInitializationEvent event) {
        // some example code
        FMLCommonHandler.instance().bus().register(new ForgeConfigChangeListener());
        FMLCommonHandler.instance().bus().register(new ForgeServerLoginListener());

        loader = Loader.instance();
    }

    @EventHandler
    public void serverStarting(FMLServerStartingEvent event){
        event.registerServerCommand(new ModCheckCmd());
    }

    public static void loadInfo(ModMetadata meta) {
        meta.modId = MLServerModChecker.MODID;
        meta.name = MLServerModChecker.NAME;
        meta.description = "Mod checker for MonsterLifeServer.";
        meta.version = MLServerModChecker.VERSION ;
        meta.url = "https://wiki.mlserver.xyz/?p=20";
        meta.authorList.add("Monster2408");
        meta.credits = "";
        meta.logoFile = "assets/mlservermodchecker/logo.png";
        meta.autogenerated = false;
    }
}
